// The size catalogue.

import type { Preset } from './domain/types.js';
//
// Search stays deliberately dumb: each preset carries marketer language,
// platform slang, format names, ratios, and use-case aliases. The builder
// also adds the preset id, group, name, orientation, and common dimension
// spellings automatically.

interface PresetInput {
  readonly id: string;
  readonly group: string;
  readonly name: string;
  readonly w: number;
  readonly h: number;
  readonly hot?: boolean;
  readonly keywords: string;
}

type RawPreset = readonly [
  id: string,
  group: string,
  name: string,
  width: number,
  height: number,
  hot: boolean,
  keywords: string,
];

const enrichPreset = ({ id, group, name, w, h, hot = false, keywords }: PresetInput): Preset => {
  const orientation = w === h
    ? ['square']
    : w > h
      ? ['landscape', 'horizontal', 'wide']
      : ['portrait', 'vertical', 'tall'];

  return {
    id,
    group,
    name,
    w,
    h,
    ...(hot ? { hot: true } : {}),
    keywords: [...new Set([
      group.toLowerCase(),
      name.toLowerCase(),
      id.replace(/-/g, ' '),
      ...orientation,
      ...keywords.split('|'),
      `${w}x${h}`,
      `${w} x ${h}`,
      `${w}×${h}`,
      `${w} by ${h}`,
      `${w}px x ${h}px`,
      `${w} ${h}`,
    ])],
  };
};

// Tuple shape: [id, group, name, width, height, hot, pipe-delimited keywords]
const RAW_PRESETS: readonly RawPreset[] = [
  // Paste these directly inside RAW_PRESETS.
  // Platform-owned upload requirements can change; these are practical
  // discovery presets and production masters, not a validation layer.

  // ---- Mastodon ----
  [
    "mastodon-square",
    "Mastodon",
    "Square post",
    1080,
    1080,
    false,
    "mastodon|fediverse|toot|post|square|1:1|timeline",
  ],
  [
    "mastodon-portrait",
    "Mastodon",
    "Portrait post",
    1080,
    1350,
    false,
    "mastodon|fediverse|toot|post|portrait|vertical|4:5|timeline",
  ],
  [
    "mastodon-landscape",
    "Mastodon",
    "Landscape post",
    1600,
    900,
    false,
    "mastodon|fediverse|toot|post|landscape|horizontal|16:9|timeline",
  ],
  [
    "mastodon-link",
    "Mastodon",
    "Link preview",
    1200,
    630,
    false,
    "mastodon|fediverse|link|preview|card|unfurl|open graph|1.91:1",
  ],
  [
    "mastodon-profile",
    "Mastodon",
    "Profile picture",
    400,
    400,
    false,
    "mastodon|fediverse|profile|avatar|pfp|display picture|account",
  ],
  [
    "mastodon-header",
    "Mastodon",
    "Profile header",
    1500,
    500,
    false,
    "mastodon|fediverse|header|banner|cover|profile|account|3:1",
  ],

  // ---- Tumblr ----
  [
    "tumblr-square",
    "Tumblr",
    "Square post",
    1080,
    1080,
    false,
    "tumblr|tumblog|post|square|dashboard|1:1",
  ],
  [
    "tumblr-portrait",
    "Tumblr",
    "Portrait post",
    1280,
    1920,
    false,
    "tumblr|tumblog|post|portrait|vertical|dashboard|2:3",
  ],
  [
    "tumblr-landscape",
    "Tumblr",
    "Landscape post",
    1280,
    720,
    false,
    "tumblr|tumblog|post|landscape|horizontal|dashboard|16:9",
  ],
  [
    "tumblr-banner",
    "Tumblr",
    "Blog header",
    3000,
    1055,
    false,
    "tumblr|tumblog|blog|header|banner|cover|theme",
  ],
  [
    "tumblr-avatar",
    "Tumblr",
    "Blog avatar",
    512,
    512,
    false,
    "tumblr|tumblog|blog|avatar|profile|pfp|icon",
  ],
  [
    "tumblr-gif",
    "Tumblr",
    "Animated GIF canvas",
    540,
    810,
    false,
    "tumblr|tumblog|gif|animated gif|reaction|loop|dashboard|vertical",
  ],

  // ---- Medium ----
  [
    "medium-hero",
    "Medium",
    "Story hero",
    2000,
    1000,
    false,
    "medium|story|article|hero|header|cover|featured image|2:1",
  ],
  [
    "medium-inline",
    "Medium",
    "Inline article image",
    1400,
    933,
    false,
    "medium|story|article|inline image|editorial|photo|3:2",
  ],
  [
    "medium-square",
    "Medium",
    "Square publication image",
    1080,
    1080,
    false,
    "medium|publication|square|social card|story card|1:1",
  ],
  [
    "medium-publication-logo",
    "Medium",
    "Publication logo",
    600,
    600,
    false,
    "medium|publication|logo|avatar|icon|brand|square",
  ],
  [
    "medium-publication-header",
    "Medium",
    "Publication header",
    1500,
    500,
    false,
    "medium|publication|header|banner|cover|masthead|3:1",
  ],
  [
    "medium-social",
    "Medium",
    "Story social preview",
    1200,
    630,
    false,
    "medium|story|article|social preview|share card|open graph|link preview",
  ],

  // ---- Substack & newsletters ----
  [
    "substack-cover",
    "Substack",
    "Publication cover",
    1100,
    220,
    false,
    "substack|publication|newsletter|cover|header|banner|masthead|5:1",
  ],
  [
    "substack-logo",
    "Substack",
    "Publication logo",
    512,
    512,
    false,
    "substack|publication|newsletter|logo|avatar|icon|square",
  ],
  [
    "substack-post",
    "Substack",
    "Post hero",
    1456,
    1048,
    false,
    "substack|newsletter|post|article|hero|cover|featured image",
  ],
  [
    "substack-social",
    "Substack",
    "Social preview",
    1200,
    630,
    false,
    "substack|newsletter|social preview|share card|open graph|link preview",
  ],
  [
    "newsletter-section",
    "Newsletter",
    "Section banner",
    1200,
    300,
    false,
    "newsletter|email|section banner|divider|strip|campaign|4:1",
  ],
  [
    "newsletter-card",
    "Newsletter",
    "Editorial card",
    1200,
    800,
    false,
    "newsletter|email|editorial card|article card|feature|content block|3:2",
  ],

  // ---- Quora & community answers ----
  [
    "quora-answer",
    "Quora",
    "Answer image",
    1200,
    675,
    false,
    "quora|answer|question|post|image|landscape|16:9",
  ],
  [
    "quora-square",
    "Quora",
    "Square post image",
    1080,
    1080,
    false,
    "quora|answer|question|post|square|1:1",
  ],
  [
    "quora-profile",
    "Quora",
    "Profile picture",
    400,
    400,
    false,
    "quora|profile|avatar|pfp|headshot|display picture",
  ],
  [
    "community-question",
    "Community",
    "Question card",
    1200,
    630,
    false,
    "community|forum|question|answer|discussion|card|share image",
  ],
  [
    "community-guide",
    "Community",
    "Guide cover",
    1600,
    900,
    false,
    "community|forum|guide|knowledge base|tutorial|cover|16:9",
  ],
  [
    "community-badge",
    "Community",
    "Member badge",
    512,
    512,
    false,
    "community|forum|member badge|role badge|achievement|icon|square",
  ],

  // ---- Local discovery ----
  [
    "nextdoor-post",
    "Local discovery",
    "Nextdoor post image",
    1200,
    900,
    false,
    "nextdoor|neighborhood|local|community|post|4:3",
  ],
  [
    "nextdoor-business",
    "Local discovery",
    "Nextdoor business cover",
    1600,
    900,
    false,
    "nextdoor|business page|local business|cover|banner|16:9",
  ],
  [
    "yelp-business-cover",
    "Local discovery",
    "Yelp business cover",
    1600,
    900,
    false,
    "yelp|business|restaurant|local|cover|hero|16:9",
  ],
  [
    "yelp-gallery",
    "Local discovery",
    "Yelp gallery photo",
    1200,
    900,
    false,
    "yelp|business|restaurant|gallery|photo|listing|4:3",
  ],
  [
    "tripadvisor-listing",
    "Local discovery",
    "Tripadvisor listing photo",
    1600,
    1200,
    false,
    "tripadvisor|trip advisor|listing|hotel|restaurant|attraction|photo|4:3",
  ],
  [
    "tripadvisor-cover",
    "Local discovery",
    "Tripadvisor cover photo",
    1920,
    1080,
    false,
    "tripadvisor|trip advisor|listing|hotel|restaurant|cover|hero|16:9",
  ],

  // ---- Travel marketplaces ----
  [
    "airbnb-listing",
    "Travel marketplace",
    "Airbnb listing photo",
    1600,
    1067,
    true,
    "airbnb|listing|vacation rental|property|travel|photo|3:2",
  ],
  [
    "airbnb-cover",
    "Travel marketplace",
    "Airbnb listing cover",
    2000,
    1333,
    false,
    "airbnb|listing|vacation rental|property|cover|hero|3:2",
  ],
  [
    "booking-listing",
    "Travel marketplace",
    "Booking listing photo",
    1600,
    1200,
    false,
    "booking.com|booking|hotel|property|listing|photo|4:3",
  ],
  [
    "expedia-listing",
    "Travel marketplace",
    "Expedia listing photo",
    1600,
    900,
    false,
    "expedia|hotel|property|listing|travel|photo|16:9",
  ],
  [
    "vrbo-listing",
    "Travel marketplace",
    "Vrbo listing photo",
    1600,
    1067,
    false,
    "vrbo|vacation rental|listing|property|travel|photo|3:2",
  ],
  [
    "travel-deal-card",
    "Travel marketplace",
    "Travel deal card",
    1200,
    630,
    false,
    "travel|deal|offer|package|hotel|flight|card|social preview",
  ],

  // ---- Product launches ----
  [
    "producthunt-gallery",
    "Product launches",
    "Product Hunt gallery",
    1270,
    760,
    false,
    "product hunt|producthunt|launch|gallery|screenshot|product page",
  ],
  [
    "producthunt-thumbnail",
    "Product launches",
    "Product Hunt thumbnail",
    240,
    240,
    false,
    "product hunt|producthunt|launch|thumbnail|logo|icon|square",
  ],
  [
    "producthunt-social",
    "Product launches",
    "Launch social card",
    1200,
    630,
    false,
    "product hunt|producthunt|launch|social card|share image|open graph",
  ],
  [
    "launch-hero",
    "Product launches",
    "Launch page hero",
    1920,
    1080,
    false,
    "product launch|launch page|hero|website|announcement|16:9",
  ],
  [
    "launch-feature",
    "Product launches",
    "Feature highlight",
    1600,
    1000,
    false,
    "product launch|feature|highlight|screenshot|benefit|product marketing",
  ],
  [
    "launch-comparison",
    "Product launches",
    "Comparison graphic",
    1600,
    1200,
    false,
    "product launch|comparison|versus|vs|competitive|matrix|4:3",
  ],

  // ---- Developer profiles ----
  [
    "github-social",
    "Developer",
    "GitHub social preview",
    1280,
    640,
    true,
    "github|repository|repo|social preview|open graph|share card|2:1",
  ],
  [
    "github-profile",
    "Developer",
    "GitHub profile picture",
    512,
    512,
    false,
    "github|profile|avatar|pfp|developer|account|square",
  ],
  [
    "github-readme-hero",
    "Developer",
    "README hero",
    1600,
    600,
    false,
    "github|readme|repository|repo|hero|banner|documentation",
  ],
  [
    "gitlab-social",
    "Developer",
    "GitLab project social preview",
    1200,
    630,
    false,
    "gitlab|project|repository|repo|social preview|open graph",
  ],
  [
    "package-social",
    "Developer",
    "Package social card",
    1200,
    630,
    false,
    "npm|pypi|package|library|sdk|social card|open graph|developer",
  ],
  [
    "docs-cover",
    "Developer",
    "Documentation cover",
    1600,
    900,
    false,
    "documentation|docs|developer portal|api docs|guide|cover|16:9",
  ],

  // ---- Creative portfolios ----
  [
    "behance-cover",
    "Creative portfolio",
    "Behance project cover",
    808,
    632,
    false,
    "behance|portfolio|project cover|creative work|case study|thumbnail",
  ],
  [
    "behance-hero",
    "Creative portfolio",
    "Behance project hero",
    1400,
    788,
    false,
    "behance|portfolio|project|hero|case study|presentation|16:9",
  ],
  [
    "dribbble-shot",
    "Creative portfolio",
    "Dribbble shot",
    1600,
    1200,
    false,
    "dribbble|shot|design|portfolio|creative|4:3",
  ],
  [
    "dribbble-profile",
    "Creative portfolio",
    "Dribbble profile picture",
    400,
    400,
    false,
    "dribbble|profile|avatar|pfp|designer|square",
  ],
  [
    "artstation-cover",
    "Creative portfolio",
    "ArtStation project cover",
    1920,
    1080,
    false,
    "artstation|portfolio|project cover|art|concept art|16:9",
  ],
  [
    "portfolio-case-study",
    "Creative portfolio",
    "Case study cover",
    1600,
    1000,
    false,
    "portfolio|case study|project cover|design process|creative work|presentation",
  ],

  // ---- Creator memberships ----
  [
    "patreon-cover",
    "Creator membership",
    "Patreon page cover",
    1600,
    400,
    false,
    "patreon|creator|membership|page cover|banner|header|4:1",
  ],
  [
    "patreon-profile",
    "Creator membership",
    "Patreon profile picture",
    512,
    512,
    false,
    "patreon|creator|membership|profile|avatar|pfp|square",
  ],
  [
    "patreon-post",
    "Creator membership",
    "Patreon post image",
    1600,
    900,
    false,
    "patreon|creator|membership|post|update|exclusive|16:9",
  ],
  [
    "kofi-cover",
    "Creator membership",
    "Ko-fi page cover",
    1200,
    400,
    false,
    "ko-fi|kofi|creator|support page|cover|banner|3:1",
  ],
  [
    "buymeacoffee-cover",
    "Creator membership",
    "Buy Me a Coffee cover",
    1600,
    400,
    false,
    "buy me a coffee|bmac|creator|support page|cover|banner|4:1",
  ],
  [
    "membership-tier",
    "Creator membership",
    "Membership tier card",
    1080,
    1080,
    false,
    "membership|creator|tier|benefits|supporter|subscription|card|square",
  ],

  // ---- Crowdfunding ----
  [
    "kickstarter-project",
    "Crowdfunding",
    "Kickstarter project image",
    1600,
    900,
    false,
    "kickstarter|crowdfunding|project image|campaign|hero|16:9",
  ],
  [
    "kickstarter-reward",
    "Crowdfunding",
    "Reward tier image",
    1200,
    900,
    false,
    "kickstarter|crowdfunding|reward|pledge|tier|product|4:3",
  ],
  [
    "indiegogo-project",
    "Crowdfunding",
    "Indiegogo campaign image",
    1600,
    900,
    false,
    "indiegogo|crowdfunding|campaign|project image|hero|16:9",
  ],
  [
    "gofundme-cover",
    "Crowdfunding",
    "GoFundMe campaign cover",
    1600,
    900,
    false,
    "gofundme|fundraiser|crowdfunding|campaign cover|hero|16:9",
  ],
  [
    "crowdfunding-social",
    "Crowdfunding",
    "Campaign social card",
    1200,
    630,
    false,
    "crowdfunding|campaign|fundraiser|social card|share image|open graph",
  ],
  [
    "crowdfunding-update",
    "Crowdfunding",
    "Campaign update image",
    1200,
    800,
    false,
    "crowdfunding|campaign|update|milestone|progress|backers|3:2",
  ],

  // ---- Event platforms ----
  [
    "meetup-cover",
    "Event platforms",
    "Meetup group cover",
    1600,
    900,
    false,
    "meetup|group|community|cover|banner|event|16:9",
  ],
  [
    "meetup-event",
    "Event platforms",
    "Meetup event image",
    1200,
    675,
    false,
    "meetup|event|event image|community|gathering|16:9",
  ],
  [
    "luma-event",
    "Event platforms",
    "Luma event cover",
    1600,
    900,
    false,
    "luma|lu.ma|event|event cover|registration|invite|16:9",
  ],
  [
    "cvent-event",
    "Event platforms",
    "Cvent event hero",
    1920,
    800,
    false,
    "cvent|event|conference|registration|hero|banner|wide",
  ],
  [
    "hopin-event",
    "Event platforms",
    "Virtual event cover",
    1920,
    1080,
    false,
    "hopin|virtual event|conference|webinar|event cover|16:9",
  ],
  [
    "event-speaker",
    "Event platforms",
    "Speaker card",
    1080,
    1350,
    false,
    "event|conference|speaker|session|agenda|announcement|4:5",
  ],

  // ---- Productivity workspaces ----
  [
    "notion-cover",
    "Productivity",
    "Notion page cover",
    1500,
    600,
    false,
    "notion|page cover|workspace|wiki|document|banner|5:2",
  ],
  [
    "notion-icon",
    "Productivity",
    "Notion page icon",
    512,
    512,
    false,
    "notion|page icon|workspace|emoji replacement|logo|square",
  ],
  [
    "trello-cover",
    "Productivity",
    "Trello card cover",
    1200,
    675,
    false,
    "trello|card cover|board|project|task|kanban|16:9",
  ],
  [
    "asana-project",
    "Productivity",
    "Asana project header",
    1600,
    400,
    false,
    "asana|project|header|banner|workspace|task management|4:1",
  ],
  [
    "monday-board",
    "Productivity",
    "Monday board header",
    1600,
    400,
    false,
    "monday.com|monday|board|header|banner|workspace|project",
  ],
  [
    "clickup-cover",
    "Productivity",
    "ClickUp document cover",
    1600,
    600,
    false,
    "clickup|document|doc|workspace|cover|header|banner",
  ],

  // ---- Collaboration & design tools ----
  [
    "airtable-cover",
    "Collaboration",
    "Airtable interface cover",
    1600,
    900,
    false,
    "airtable|base|interface|cover|dashboard|workspace|16:9",
  ],
  [
    "confluence-header",
    "Collaboration",
    "Confluence page header",
    1600,
    500,
    false,
    "confluence|wiki|page header|documentation|workspace|banner",
  ],
  [
    "jira-project",
    "Collaboration",
    "Jira project image",
    1200,
    630,
    false,
    "jira|project|issue tracker|software team|project image|social card",
  ],
  [
    "miro-board-cover",
    "Collaboration",
    "Miro board cover",
    1600,
    900,
    false,
    "miro|whiteboard|board cover|workshop|canvas|collaboration|16:9",
  ],
  [
    "figma-community",
    "Collaboration",
    "Figma Community thumbnail",
    1600,
    960,
    false,
    "figma|community|file cover|plugin cover|template|design resource",
  ],
  [
    "framer-template",
    "Collaboration",
    "Framer template cover",
    1600,
    1000,
    false,
    "framer|template|website template|marketplace|cover|preview",
  ],

  // ---- CMS & site builders ----
  [
    "wordpress-featured",
    "CMS",
    "WordPress featured image",
    1200,
    675,
    false,
    "wordpress|wp|featured image|blog|article|post thumbnail|16:9",
  ],
  [
    "wordpress-site-icon",
    "CMS",
    "WordPress site icon",
    512,
    512,
    false,
    "wordpress|wp|site icon|favicon|logo|square",
  ],
  [
    "ghost-feature",
    "CMS",
    "Ghost post feature image",
    1600,
    900,
    false,
    "ghost|publication|post|feature image|article|newsletter|16:9",
  ],
  [
    "squarespace-banner",
    "CMS",
    "Squarespace section banner",
    2500,
    1200,
    false,
    "squarespace|website|section banner|hero|cover|wide",
  ],
  [
    "wix-strip",
    "CMS",
    "Wix strip background",
    1920,
    800,
    false,
    "wix|website|strip|section background|hero|banner|wide",
  ],
  [
    "webflow-social",
    "CMS",
    "Webflow social preview",
    1200,
    630,
    false,
    "webflow|website|social preview|open graph|share card|link preview",
  ],

  // ---- Lifecycle marketing ----
  [
    "mailchimp-campaign",
    "Lifecycle marketing",
    "Mailchimp campaign hero",
    1200,
    600,
    false,
    "mailchimp|email|campaign|newsletter|hero|banner|2:1",
  ],
  [
    "klaviyo-flow",
    "Lifecycle marketing",
    "Klaviyo flow hero",
    1200,
    600,
    false,
    "klaviyo|email|flow|automation|campaign|hero|2:1",
  ],
  [
    "beehiiv-post",
    "Lifecycle marketing",
    "Beehiiv post cover",
    1600,
    900,
    false,
    "beehiiv|newsletter|publication|post cover|article|16:9",
  ],
  [
    "braze-content-card",
    "Lifecycle marketing",
    "Braze content card",
    1200,
    628,
    false,
    "braze|content card|in-app message|lifecycle|campaign|1.91:1",
  ],
  [
    "customerio-message",
    "Lifecycle marketing",
    "Customer.io message hero",
    1200,
    600,
    false,
    "customer.io|customerio|email|message|campaign|hero|2:1",
  ],
  [
    "hubspot-cta",
    "Lifecycle marketing",
    "HubSpot CTA graphic",
    1200,
    400,
    false,
    "hubspot|cta|call to action|campaign|landing page|banner|3:1",
  ],

  // ---- Notifications & messaging ----
  [
    "push-landscape",
    "Notifications",
    "Push notification image",
    1200,
    600,
    false,
    "push notification|mobile push|rich push|notification image|2:1",
  ],
  [
    "push-square",
    "Notifications",
    "Push notification square",
    1024,
    1024,
    false,
    "push notification|mobile push|rich push|square|icon|1:1",
  ],
  [
    "inapp-modal",
    "Notifications",
    "In-app modal",
    1080,
    1350,
    false,
    "in-app message|in app|modal|popup|mobile|campaign|4:5",
  ],
  [
    "inapp-banner",
    "Notifications",
    "In-app banner",
    1200,
    300,
    false,
    "in-app message|in app|banner|strip|mobile|campaign|4:1",
  ],
  [
    "mms-image",
    "Notifications",
    "MMS campaign image",
    1200,
    1200,
    false,
    "mms|sms marketing|text message|campaign image|mobile message|square",
  ],
  [
    "rcs-card",
    "Notifications",
    "RCS rich card",
    1200,
    900,
    false,
    "rcs|rich communication services|rich card|message|carousel card|4:3",
  ],

  // ---- Wallet passes & tickets ----
  [
    "wallet-event",
    "Wallet passes",
    "Event pass hero",
    1125,
    432,
    false,
    "apple wallet|google wallet|event pass|ticket|hero|strip",
  ],
  [
    "wallet-boarding",
    "Wallet passes",
    "Boarding pass strip",
    1125,
    432,
    false,
    "apple wallet|google wallet|boarding pass|flight|travel|strip",
  ],
  [
    "wallet-loyalty",
    "Wallet passes",
    "Loyalty card art",
    1125,
    432,
    false,
    "apple wallet|google wallet|loyalty card|rewards|membership|strip",
  ],
  [
    "wallet-coupon",
    "Wallet passes",
    "Coupon pass art",
    1125,
    432,
    false,
    "apple wallet|google wallet|coupon|offer|discount|voucher|strip",
  ],
  [
    "digital-ticket",
    "Wallet passes",
    "Digital ticket",
    1080,
    1920,
    false,
    "digital ticket|mobile ticket|event ticket|qr code|admission|9:16",
  ],
  [
    "membership-card",
    "Wallet passes",
    "Digital membership card",
    1080,
    680,
    false,
    "membership card|digital card|loyalty|club|member id|landscape",
  ],

  // ---- Browser & SaaS marketplaces ----
  [
    "chrome-store-tile",
    "Marketplaces",
    "Chrome Web Store tile",
    1280,
    800,
    false,
    "chrome web store|browser extension|extension|store tile|listing|5:3",
  ],
  [
    "firefox-addon-card",
    "Marketplaces",
    "Firefox Add-ons card",
    1200,
    800,
    false,
    "firefox|mozilla|add-on|browser extension|listing|card|3:2",
  ],
  [
    "edge-addon-tile",
    "Marketplaces",
    "Edge Add-ons tile",
    1280,
    800,
    false,
    "microsoft edge|edge add-ons|browser extension|store tile|listing",
  ],
  [
    "slack-app-icon",
    "Marketplaces",
    "Slack app icon",
    512,
    512,
    false,
    "slack|app directory|app icon|integration|bot|square",
  ],
  [
    "atlassian-listing",
    "Marketplaces",
    "Atlassian Marketplace listing",
    1200,
    630,
    false,
    "atlassian|marketplace|jira app|confluence app|listing|social card",
  ],
  [
    "appexchange-tile",
    "Marketplaces",
    "Salesforce AppExchange tile",
    1200,
    900,
    false,
    "salesforce|appexchange|app listing|integration|marketplace|4:3",
  ],

  // ---- Steam ----
  [
    "steam-header-capsule",
    "Steam",
    "Header capsule",
    920,
    430,
    true,
    "steam|steamworks|game|header capsule|store capsule|store page",
  ],
  [
    "steam-small-capsule",
    "Steam",
    "Small capsule",
    462,
    174,
    false,
    "steam|steamworks|game|small capsule|store capsule|library",
  ],
  [
    "steam-main-capsule",
    "Steam",
    "Main capsule",
    1232,
    706,
    false,
    "steam|steamworks|game|main capsule|store capsule|featured",
  ],
  [
    "steam-vertical-capsule",
    "Steam",
    "Vertical capsule",
    748,
    896,
    false,
    "steam|steamworks|game|vertical capsule|store capsule|portrait",
  ],
  [
    "steam-library-hero",
    "Steam",
    "Library hero",
    3840,
    1240,
    false,
    "steam|steamworks|game|library hero|banner|game library|wide",
  ],
  [
    "steam-library-logo",
    "Steam",
    "Library logo",
    1280,
    720,
    false,
    "steam|steamworks|game|library logo|transparent logo|branding|16:9",
  ],

  // ---- Gaming marketplaces ----
  [
    "epic-game-tile",
    "Gaming marketplace",
    "Epic Games Store tile",
    1200,
    1600,
    false,
    "epic games|egs|game store|tile|cover|portrait|3:4",
  ],
  [
    "epic-game-hero",
    "Gaming marketplace",
    "Epic Games Store hero",
    2560,
    1440,
    false,
    "epic games|egs|game store|hero|key art|16:9",
  ],
  [
    "itch-cover",
    "Gaming marketplace",
    "itch.io cover",
    630,
    500,
    false,
    "itch.io|itchio|indie game|game cover|store page|listing",
  ],
  [
    "xbox-store-hero",
    "Gaming marketplace",
    "Xbox store hero",
    1920,
    1080,
    false,
    "xbox|microsoft store|game|store hero|key art|16:9",
  ],
  [
    "playstation-keyart",
    "Gaming marketplace",
    "PlayStation key art",
    1920,
    1080,
    false,
    "playstation|ps5|ps4|game|key art|store image|16:9",
  ],
  [
    "nintendo-eshop",
    "Gaming marketplace",
    "Nintendo eShop hero",
    1920,
    1080,
    false,
    "nintendo|eshop|switch|game|hero|key art|16:9",
  ],

  // ---- Creator gaming & communities ----
  [
    "roblox-icon",
    "Gaming community",
    "Roblox experience icon",
    512,
    512,
    false,
    "roblox|experience|game icon|thumbnail|square|ugc",
  ],
  [
    "roblox-thumbnail",
    "Gaming community",
    "Roblox experience thumbnail",
    1920,
    1080,
    false,
    "roblox|experience|game thumbnail|cover|16:9|ugc",
  ],
  [
    "minecraft-marketplace",
    "Gaming community",
    "Minecraft Marketplace cover",
    1920,
    1080,
    false,
    "minecraft|marketplace|world|skin pack|texture pack|cover|16:9",
  ],
  [
    "discord-activity",
    "Gaming community",
    "Discord activity cover",
    1920,
    1080,
    false,
    "discord|activity|embedded app|game|cover|16:9",
  ],
  [
    "twitch-extension",
    "Gaming community",
    "Twitch extension tile",
    600,
    400,
    false,
    "twitch|extension|overlay app|panel app|listing|3:2",
  ],
  [
    "gaming-clan-banner",
    "Gaming community",
    "Clan banner",
    1920,
    480,
    false,
    "gaming|clan|guild|team|esports|banner|header|4:1",
  ],

  // ---- TV & OTT ----
  [
    "roku-channel-poster",
    "TV & OTT",
    "Roku channel poster",
    540,
    405,
    false,
    "roku|channel|poster|app tile|tv app|4:3",
  ],
  [
    "firetv-background",
    "TV & OTT",
    "Fire TV background",
    1920,
    1080,
    false,
    "amazon fire tv|firetv|tv app|background|hero|16:9",
  ],
  [
    "appletv-top-shelf",
    "TV & OTT",
    "Apple TV top shelf",
    1920,
    720,
    false,
    "apple tv|tvos|top shelf|hero|banner|tv app",
  ],
  [
    "samsungtv-tile",
    "TV & OTT",
    "Samsung TV app tile",
    512,
    512,
    false,
    "samsung tv|tizen|tv app|app tile|icon|square",
  ],
  [
    "lgtv-tile",
    "TV & OTT",
    "LG TV app tile",
    512,
    512,
    false,
    "lg tv|webos|tv app|app tile|icon|square",
  ],
  [
    "ott-feature",
    "TV & OTT",
    "OTT featured content hero",
    3840,
    2160,
    false,
    "ott|streaming|tv app|featured content|hero|key art|4k|16:9",
  ],

  // ---- Music artist platforms ----
  [
    "spotify-artist-header",
    "Music platforms",
    "Spotify artist header",
    2660,
    1140,
    false,
    "spotify|artist|header|banner|profile|music",
  ],
  [
    "spotify-release",
    "Music platforms",
    "Release cover",
    3000,
    3000,
    false,
    "spotify|album|single|release|cover art|music|square",
  ],
  [
    "applemusic-artist",
    "Music platforms",
    "Apple Music artist image",
    2400,
    2400,
    false,
    "apple music|artist|profile|artist image|music|square",
  ],
  [
    "bandcamp-header",
    "Music platforms",
    "Bandcamp header",
    975,
    180,
    false,
    "bandcamp|artist|label|header|banner|music",
  ],
  [
    "deezer-artist",
    "Music platforms",
    "Deezer artist image",
    1200,
    1200,
    false,
    "deezer|artist|profile|music|avatar|square",
  ],
  [
    "audiomack-cover",
    "Music platforms",
    "Audiomack release cover",
    3000,
    3000,
    false,
    "audiomack|album|single|mixtape|cover art|music|square",
  ],

  // ---- Podcast, audio & books ----
  [
    "podcast-episode",
    "Publishing",
    "Podcast episode art",
    3000,
    3000,
    false,
    "podcast|episode art|episode cover|audio|show|square",
  ],
  [
    "audiobook-cover",
    "Publishing",
    "Audiobook cover",
    2400,
    2400,
    false,
    "audiobook|audible|audio book|cover|publishing|square",
  ],
  [
    "kindle-cover",
    "Publishing",
    "Kindle ebook cover",
    1600,
    2560,
    true,
    "kindle|ebook|amazon kdp|book cover|publishing|1:1.6",
  ],
  [
    "print-book-cover",
    "Publishing",
    "Trade paperback front cover",
    1800,
    2700,
    false,
    "book cover|paperback|novel|publishing|front cover|2:3",
  ],
  [
    "wattpad-cover",
    "Publishing",
    "Wattpad story cover",
    512,
    800,
    false,
    "wattpad|story|book cover|fiction|publishing|vertical",
  ],
  [
    "author-media-kit",
    "Publishing",
    "Author media kit cover",
    2550,
    3300,
    false,
    "author|media kit|press kit|book launch|publishing|letter",
  ],

  // ---- Documents & editorial ----
  [
    "whitepaper-cover",
    "Documents",
    "White paper cover",
    2480,
    3508,
    false,
    "white paper|whitepaper|report|lead magnet|pdf|a4|cover",
  ],
  [
    "case-study-cover",
    "Documents",
    "Case study cover",
    2550,
    3300,
    false,
    "case study|customer story|success story|report|pdf|letter|cover",
  ],
  [
    "annual-report-cover",
    "Documents",
    "Annual report cover",
    2480,
    3508,
    false,
    "annual report|company report|investor report|pdf|a4|cover",
  ],
  [
    "proposal-cover",
    "Documents",
    "Proposal cover",
    2550,
    3300,
    false,
    "proposal|pitch|statement of work|sow|document|letter|cover",
  ],
  [
    "resume-letter",
    "Documents",
    "Resume — US Letter",
    2550,
    3300,
    false,
    "resume|cv|curriculum vitae|job application|us letter|document",
  ],
  [
    "press-kit-cover",
    "Documents",
    "Press kit cover",
    1920,
    1080,
    false,
    "press kit|media kit|brand kit|public relations|pr|cover|16:9",
  ],

  // ---- Print marketing & events ----
  [
    "print-flyer-letter",
    "Print marketing",
    "Flyer — US Letter",
    2550,
    3300,
    false,
    "flyer|print|marketing|us letter|8.5x11|300dpi",
  ],
  [
    "print-flyer-a4",
    "Print marketing",
    "Flyer — A4",
    2480,
    3508,
    false,
    "flyer|print|marketing|a4|300dpi|handout",
  ],
  [
    "print-menu-letter",
    "Print marketing",
    "Menu — US Letter",
    2550,
    3300,
    false,
    "menu|restaurant|print|us letter|food|drinks|300dpi",
  ],
  [
    "print-table-tent",
    "Print marketing",
    "Table tent — 5 × 7",
    1500,
    2100,
    false,
    "table tent|restaurant|event|counter card|5x7|300dpi",
  ],
  [
    "print-event-ticket",
    "Print marketing",
    "Event ticket — 2 × 5.5",
    1650,
    600,
    false,
    "event ticket|admission|concert|festival|2x5.5|300dpi",
  ],
  [
    "print-event-badge",
    "Print marketing",
    "Event badge — 4 × 6",
    1200,
    1800,
    false,
    "event badge|conference badge|name badge|credential|4x6|300dpi",
  ],

  // ---- Packaging & labels ----
  [
    "package-box-front",
    "Packaging",
    "Product box front",
    2400,
    3000,
    false,
    "packaging|product box|box front|retail package|carton|4:5",
  ],
  [
    "package-bottle-label",
    "Packaging",
    "Bottle label",
    1800,
    1200,
    false,
    "packaging|bottle label|beverage|cosmetics|label|3:2",
  ],
  [
    "package-can-label",
    "Packaging",
    "Can wrap label",
    3000,
    1200,
    false,
    "packaging|can label|beverage can|wrap label|cylinder|5:2",
  ],
  [
    "package-pouch-front",
    "Packaging",
    "Pouch front",
    2000,
    2500,
    false,
    "packaging|pouch|stand up pouch|food package|bag|4:5",
  ],
  [
    "package-jar-label",
    "Packaging",
    "Jar label",
    2400,
    900,
    false,
    "packaging|jar label|food|cosmetics|wrap label|8:3",
  ],
  [
    "shipping-label",
    "Packaging",
    "Shipping label — 4 × 6",
    1200,
    1800,
    false,
    "shipping label|parcel|package|fulfillment|4x6|300dpi",
  ],

  // ---- Merchandise & apparel ----
  [
    "merch-tshirt-front",
    "Merchandise",
    "T-shirt front print",
    4500,
    5400,
    true,
    "t-shirt|tshirt|shirt|apparel|print on demand|pod|front print",
  ],
  [
    "merch-hoodie-front",
    "Merchandise",
    "Hoodie front print",
    4500,
    5400,
    false,
    "hoodie|sweatshirt|apparel|print on demand|pod|front print",
  ],
  [
    "merch-tote",
    "Merchandise",
    "Tote bag print",
    3600,
    4200,
    false,
    "tote bag|bag|merch|print on demand|pod|apparel",
  ],
  [
    "merch-mug",
    "Merchandise",
    "Mug wrap",
    2700,
    1125,
    false,
    "mug|coffee mug|drinkware|wrap|print on demand|pod",
  ],
  [
    "merch-sticker",
    "Merchandise",
    "Sticker sheet",
    2550,
    3300,
    false,
    "sticker|sticker sheet|decal|merch|print|us letter",
  ],
  [
    "merch-decal",
    "Merchandise",
    "Die-cut decal",
    2400,
    2400,
    false,
    "decal|die cut|sticker|vinyl|merch|square master",
  ],

  // ---- Outdoor & transit ----
  [
    "ooh-billboard",
    "Outdoor advertising",
    "Roadside billboard — 14 × 48",
    4800,
    1400,
    false,
    "billboard|out of home|ooh|roadside|14x48|wide",
  ],
  [
    "ooh-digital-billboard",
    "Outdoor advertising",
    "Digital billboard — 16:9",
    1920,
    1080,
    false,
    "digital billboard|out of home|ooh|screen|16:9",
  ],
  [
    "ooh-bus-shelter",
    "Outdoor advertising",
    "Bus shelter poster",
    1800,
    2700,
    false,
    "bus shelter|transit ad|out of home|ooh|poster|2:3",
  ],
  [
    "ooh-bus-side",
    "Outdoor advertising",
    "Bus side panel",
    3600,
    1200,
    false,
    "bus ad|bus side|transit ad|out of home|ooh|3:1",
  ],
  [
    "ooh-subway",
    "Outdoor advertising",
    "Subway platform poster",
    2400,
    3600,
    false,
    "subway|metro|platform poster|transit ad|out of home|2:3",
  ],
  [
    "ooh-airport",
    "Outdoor advertising",
    "Airport digital display",
    2160,
    3840,
    false,
    "airport|digital display|portrait screen|out of home|ooh|9:16",
  ],

  // ---- Trade show & retail signage ----
  [
    "trade-backdrop",
    "Signage",
    "Trade show backdrop",
    3600,
    2400,
    false,
    "trade show|backdrop|step and repeat|booth|conference|3:2",
  ],
  [
    "trade-rollup",
    "Signage",
    "Roll-up banner",
    2550,
    7200,
    false,
    "roll up banner|retractable banner|trade show|display|portrait",
  ],
  [
    "trade-counter",
    "Signage",
    "Counter graphic",
    2400,
    1200,
    false,
    "trade show|counter|booth|display|front graphic|2:1",
  ],
  [
    "retail-poster",
    "Signage",
    "Retail poster",
    3600,
    5400,
    false,
    "retail|poster|store|promotion|sale|2:3",
  ],
  [
    "retail-window",
    "Signage",
    "Window graphic",
    3600,
    3600,
    false,
    "retail|window graphic|storefront|decal|promotion|square",
  ],
  [
    "retail-shelf",
    "Signage",
    "Shelf talker",
    1800,
    900,
    false,
    "retail|shelf talker|point of sale|pos|product promotion|2:1",
  ],

  // ---- Education & e-learning ----
  [
    "course-thumbnail",
    "Education",
    "Course thumbnail",
    1280,
    720,
    true,
    "course|online course|class|lesson|thumbnail|e-learning|16:9",
  ],
  [
    "lms-banner",
    "Education",
    "LMS course banner",
    1600,
    400,
    false,
    "lms|learning management system|course banner|class header|4:1",
  ],
  [
    "certificate-landscape",
    "Education",
    "Certificate — landscape",
    3300,
    2550,
    false,
    "certificate|award|completion|diploma|landscape|letter|300dpi",
  ],
  [
    "worksheet-letter",
    "Education",
    "Worksheet — US Letter",
    2550,
    3300,
    false,
    "worksheet|classroom|education|lesson|activity|us letter",
  ],
  [
    "flashcard",
    "Education",
    "Flash card — 5 × 3",
    1500,
    900,
    false,
    "flashcard|study card|education|quiz|5x3|300dpi",
  ],
  [
    "classroom-poster",
    "Education",
    "Classroom poster — 18 × 24",
    5400,
    7200,
    false,
    "classroom poster|education|school|learning|18x24|300dpi",
  ],

  // ---- Real estate & recruiting ----
  [
    "realestate-listing",
    "Listings",
    "Property listing hero",
    1920,
    1080,
    true,
    "real estate|property|listing|mls|home|house|hero|16:9",
  ],
  [
    "realestate-brochure",
    "Listings",
    "Property brochure",
    2550,
    3300,
    false,
    "real estate|property|brochure|listing sheet|home|us letter",
  ],
  [
    "realestate-openhouse",
    "Listings",
    "Open house post",
    1080,
    1350,
    false,
    "real estate|open house|property|social post|4:5|realtor",
  ],
  [
    "job-card",
    "Listings",
    "Job listing card",
    1200,
    630,
    false,
    "job|hiring|career|vacancy|job listing|recruiting|social card",
  ],
  [
    "indeed-employer",
    "Listings",
    "Employer brand banner",
    1600,
    500,
    false,
    "indeed|employer|company|career|hiring|banner|header",
  ],
  [
    "glassdoor-employer",
    "Listings",
    "Company profile cover",
    1600,
    500,
    false,
    "glassdoor|employer|company|career|profile cover|banner",
  ],

  // ---- Food, hospitality & delivery ----
  [
    "restaurant-hero",
    "Hospitality",
    "Restaurant website hero",
    1920,
    1080,
    false,
    "restaurant|food|website|hero|dining|hospitality|16:9",
  ],
  [
    "doordash-item",
    "Hospitality",
    "DoorDash menu item",
    1200,
    900,
    false,
    "doordash|door dash|menu item|food delivery|restaurant|4:3",
  ],
  [
    "ubereats-item",
    "Hospitality",
    "Uber Eats menu item",
    1200,
    900,
    false,
    "uber eats|ubereats|menu item|food delivery|restaurant|4:3",
  ],
  [
    "grubhub-item",
    "Hospitality",
    "Grubhub menu item",
    1200,
    900,
    false,
    "grubhub|menu item|food delivery|restaurant|4:3",
  ],
  [
    "hotel-amenity",
    "Hospitality",
    "Hotel amenity card",
    1200,
    800,
    false,
    "hotel|amenity|hospitality|resort|room feature|card|3:2",
  ],
  [
    "hotel-offer",
    "Hospitality",
    "Hotel offer banner",
    1600,
    900,
    false,
    "hotel|resort|offer|package|promotion|travel|16:9",
  ],

  // ---- Travel operations ----
  [
    "travel-itinerary",
    "Travel operations",
    "Travel itinerary — Letter",
    2550,
    3300,
    true,
    "travel itinerary|trip plan|vacation|tour|schedule|us letter",
  ],
  [
    "boarding-pass",
    "Travel operations",
    "Boarding pass",
    1800,
    750,
    false,
    "boarding pass|flight|airline|ticket|travel|12:5",
  ],
  [
    "hotel-voucher",
    "Travel operations",
    "Hotel voucher",
    1800,
    1200,
    false,
    "hotel voucher|reservation|booking|travel document|3:2",
  ],
  [
    "tour-ticket",
    "Travel operations",
    "Tour ticket",
    1800,
    750,
    false,
    "tour ticket|attraction ticket|excursion|travel|admission|12:5",
  ],
  [
    "cruise-planner",
    "Travel operations",
    "Cruise daily planner",
    2550,
    3300,
    false,
    "cruise|daily planner|ship schedule|travel|itinerary|us letter",
  ],
  [
    "map-card",
    "Travel operations",
    "Destination map card",
    1600,
    1200,
    false,
    "map|destination|travel guide|route|city guide|4:3",
  ],

  // ---- Devices, wallpaper & video ----
  [
    "device-phone-portrait",
    "Digital canvas",
    "Phone screen — portrait",
    1170,
    2532,
    false,
    "phone screen|mobile ui|iphone|android|app mockup|portrait",
  ],
  [
    "device-tablet-portrait",
    "Digital canvas",
    "Tablet screen — portrait",
    2048,
    2732,
    false,
    "tablet screen|ipad|android tablet|app mockup|portrait",
  ],
  [
    "wallpaper-desktop",
    "Digital canvas",
    "Desktop wallpaper",
    2560,
    1440,
    false,
    "desktop wallpaper|computer background|monitor|qhd|16:9",
  ],
  [
    "wallpaper-ultrawide",
    "Digital canvas",
    "Ultrawide wallpaper",
    3440,
    1440,
    false,
    "ultrawide wallpaper|monitor background|21:9|desktop",
  ],
  [
    "video-lower-third",
    "Digital canvas",
    "Video lower third",
    1920,
    300,
    false,
    "lower third|video graphic|name strap|broadcast|title bar",
  ],
  [
    "video-end-card",
    "Digital canvas",
    "Video end card",
    1920,
    1080,
    false,
    "video end card|end screen|outro|subscribe|cta|16:9",
  ],

  // ---- Paid media expansions ----
  [
    "gads-pmax-landscape",
    "Paid media",
    "Google Ads landscape asset",
    1200,
    628,
    true,
    "google ads|performance max|pmax|landscape asset|paid media|1.91:1",
  ],
  [
    "gads-pmax-square",
    "Paid media",
    "Google Ads square asset",
    1200,
    1200,
    true,
    "google ads|performance max|pmax|square asset|paid media|1:1",
  ],
  [
    "gads-pmax-portrait",
    "Paid media",
    "Google Ads portrait asset",
    960,
    1200,
    false,
    "google ads|performance max|pmax|portrait asset|paid media|4:5",
  ],
  [
    "meta-carousel",
    "Paid media",
    "Meta carousel card",
    1080,
    1080,
    true,
    "meta ads|facebook ads|instagram ads|carousel|card|paid social|1:1",
  ],
  [
    "linkedin-ad-landscape",
    "Paid media",
    "LinkedIn ad — landscape",
    1200,
    628,
    false,
    "linkedin ads|sponsored content|paid social|landscape ad|1.91:1",
  ],
  [
    "reddit-ad-card",
    "Paid media",
    "Reddit ad card",
    1200,
    628,
    false,
    "reddit ads|promoted post|paid social|ad card|landscape|1.91:1",
  ],
  
  // ---- Instagram ----
  ["ig-square", "Instagram", "Square post", 1080, 1080, true, "ig|insta|instagram|square|feed|post|1:1|grid|carousel|album"],
  ["ig-portrait", "Instagram", "Portrait post", 1080, 1350, true, "ig|insta|instagram|tall|portrait|vertical|4:5|feed|carousel|biggest|more feed|takes up more feed"],
  ["ig-landscape", "Instagram", "Landscape post", 1080, 566, false, "ig|insta|instagram|wide|landscape|horizontal|feed|1.91:1"],
  ["ig-story", "Instagram", "Story", 1080, 1920, true, "ig|insta|instagram|story|stories|vertical|fullscreen|full screen|9:16|phone"],
  ["ig-reel", "Instagram", "Reel", 1080, 1920, true, "ig|insta|instagram|reel|reels|vertical video|short video|fullscreen|9:16"],
  ["ig-reel-cover", "Instagram", "Reel cover", 1080, 1920, false, "ig|insta|instagram|reel cover|reels cover|cover|thumbnail|poster frame"],
  ["ig-highlight", "Instagram", "Highlight cover", 1080, 1080, false, "ig|insta|instagram|highlight|highlights|story highlight|cover|icon|circle"],
  ["ig-profile", "Instagram", "Profile picture", 320, 320, false, "ig|insta|instagram|profile|avatar|pfp|headshot|dp|display picture"],
  ["ig-ad-square", "Instagram", "Square ad", 1080, 1080, false, "ig|instagram|ad|ads|paid social|sponsored|square ad|1:1"],
  ["ig-ad-portrait", "Instagram", "Portrait ad", 1080, 1350, false, "ig|instagram|ad|ads|paid social|sponsored|portrait ad|4:5"],

  // ---- Threads ----
  ["threads-square", "Threads", "Square post", 1080, 1080, false, "threads|meta threads|square|post|feed|1:1"],
  ["threads-portrait", "Threads", "Portrait post", 1080, 1350, false, "threads|meta threads|portrait|tall|vertical|post|feed|4:5"],
  ["threads-landscape", "Threads", "Landscape post", 1080, 566, false, "threads|meta threads|landscape|wide|horizontal|post|feed"],
  ["threads-profile", "Threads", "Profile picture", 320, 320, false, "threads|meta threads|profile|avatar|pfp|display picture"],

  // ---- TikTok ----
  ["tiktok-video", "TikTok", "Vertical video", 1080, 1920, true, "tiktok|tik tok|video|vertical|fullscreen|full screen|9:16|short video|for you|fyp"],
  ["tiktok-cover", "TikTok", "Video cover", 1080, 1920, false, "tiktok|tik tok|cover|thumbnail|video cover|poster|poster frame"],
  ["tiktok-carousel", "TikTok", "Photo carousel", 1080, 1920, false, "tiktok|tik tok|photo mode|carousel|slideshow|photos|vertical|9:16"],
  ["tiktok-square", "TikTok", "Square video", 1080, 1080, false, "tiktok|tik tok|square|video|1:1"],
  ["tiktok-landscape", "TikTok", "Landscape video", 1920, 1080, false, "tiktok|tik tok|landscape|horizontal|wide|video|16:9"],
  ["tiktok-profile", "TikTok", "Profile picture", 200, 200, false, "tiktok|tik tok|profile|avatar|pfp|display picture"],
  ["tiktok-ad-square", "TikTok", "Carousel ad — square", 640, 640, false, "tiktok|tik tok|ad|ads|carousel ad|square ad|1:1|paid social"],
  ["tiktok-ad-landscape", "TikTok", "Carousel ad — landscape", 1200, 628, false, "tiktok|tik tok|ad|ads|carousel ad|landscape ad|horizontal|1.91:1|paid social"],

  // ---- Facebook ----
  ["fb-feed", "Facebook", "Feed / link image", 1200, 630, true, "fb|facebook|feed|link|shared link|share|post|meta|link image|website preview"],
  ["fb-square", "Facebook", "Square post", 1080, 1080, false, "fb|facebook|square|post|feed|1:1"],
  ["fb-portrait", "Facebook", "Portrait post", 1080, 1350, false, "fb|facebook|portrait|tall|vertical|post|feed|4:5"],
  ["fb-story", "Facebook", "Story", 1080, 1920, false, "fb|facebook|story|stories|vertical|fullscreen|9:16"],
  ["fb-reel", "Facebook", "Reel", 1080, 1920, false, "fb|facebook|reel|reels|vertical video|short video|9:16"],
  ["fb-cover", "Facebook", "Page cover", 1640, 624, false, "fb|facebook|cover|banner|header|page|business page|timeline cover"],
  ["fb-profile", "Facebook", "Profile picture", 320, 320, false, "fb|facebook|profile|avatar|pfp|display picture|page logo"],
  ["fb-event", "Facebook", "Event cover", 1920, 1005, false, "fb|facebook|event|cover|banner|event image|event header"],
  ["fb-group-cover", "Facebook", "Group cover", 1640, 856, false, "fb|facebook|group|community|cover|banner|header"],
  ["fb-carousel", "Facebook", "Carousel card", 1080, 1080, false, "fb|facebook|carousel|card|multi image|ad|square|1:1"],
  ["fb-marketplace", "Facebook", "Marketplace listing", 1200, 1200, false, "fb|facebook|marketplace|listing|product|commerce|shop|square"],

  // ---- Messenger ----
  ["messenger-story", "Messenger", "Story ad", 1080, 1920, false, "messenger|facebook messenger|story|story ad|vertical ad|fullscreen|9:16"],
  ["messenger-inbox-ad", "Messenger", "Inbox ad", 1200, 628, false, "messenger|facebook messenger|inbox ad|sponsored|ad|landscape|1.91:1"],
  ["messenger-profile", "Messenger", "Profile picture", 640, 640, false, "messenger|facebook messenger|profile|avatar|pfp|display picture"],

  // ---- X / Twitter ----
  ["x-post", "X / Twitter", "Post image", 1600, 900, true, "x|twitter|tweet|post|timeline|card|16:9|landscape|wide"],
  ["x-square", "X / Twitter", "Square post", 1080, 1080, false, "x|twitter|tweet|square|post|1:1"],
  ["x-portrait", "X / Twitter", "Portrait post", 1080, 1350, false, "x|twitter|tweet|portrait|tall|vertical|post|4:5"],
  ["x-header", "X / Twitter", "Profile header", 1500, 500, false, "x|twitter|header|banner|cover|profile|3:1"],
  ["x-profile", "X / Twitter", "Profile picture", 400, 400, false, "x|twitter|profile|avatar|pfp|display picture"],
  ["x-website-card", "X / Twitter", "Website card", 1200, 628, false, "x|twitter|website card|link card|link preview|summary card|large image|1.91:1"],
  ["x-ad-portrait", "X / Twitter", "Portrait ad", 1080, 1350, false, "x|twitter|ad|ads|sponsored|paid social|portrait ad|4:5"],

  // ---- LinkedIn ----
  ["li-post", "LinkedIn", "Feed / link post", 1200, 627, true, "linkedin|li|post|feed|share|link|article|1.91:1|b2b"],
  ["li-square", "LinkedIn", "Square post", 1080, 1080, false, "linkedin|li|square|post|feed|carousel|document|1:1"],
  ["li-portrait", "LinkedIn", "Portrait post", 1080, 1350, false, "linkedin|li|portrait|tall|vertical|post|feed|document|4:5"],
  ["li-profile", "LinkedIn", "Profile picture", 400, 400, false, "linkedin|li|profile|headshot|avatar|pfp|professional photo"],
  ["li-cover", "LinkedIn", "Profile cover", 1584, 396, false, "linkedin|li|cover|banner|header|background|personal profile|4:1"],
  ["li-company-logo", "LinkedIn", "Company logo", 400, 400, false, "linkedin|li|company|page|logo|brand|avatar|square"],
  ["li-company", "LinkedIn", "Company page cover", 1128, 191, false, "linkedin|li|company|page|cover|banner|header|business page"],
  ["li-event", "LinkedIn", "Event cover", 1776, 444, false, "linkedin|li|event|cover|banner|header|4:1"],
  ["li-life-main", "LinkedIn", "Life tab main image", 1128, 376, false, "linkedin|li|life tab|career page|employer brand|main image|3:1"],
  ["li-life-module", "LinkedIn", "Life tab custom module", 502, 282, false, "linkedin|li|life tab|career page|custom module|module image|16:9"],
  ["li-article-cover", "LinkedIn", "Article cover", 1280, 720, false, "linkedin|li|article|newsletter|cover|hero|featured image|16:9"],
  ["li-message-ad", "LinkedIn", "Message ad image", 300, 250, false, "linkedin|li|message ad|conversation ad|sponsored message|inmail|medium rectangle"],

  // ---- YouTube ----
  ["yt-thumb", "YouTube", "Video thumbnail", 1280, 720, true, "youtube|yt|thumb|thumbnail|video|16:9|preview|cover"],
  ["yt-shorts", "YouTube", "Shorts video", 1080, 1920, true, "youtube|yt|shorts|short|vertical|9:16|short video"],
  ["yt-shorts-thumb", "YouTube", "Shorts thumbnail", 2160, 3840, false, "youtube|yt|shorts thumbnail|shorts cover|vertical thumbnail|9:16"],
  ["yt-banner", "YouTube", "Channel banner", 2560, 1440, false, "youtube|yt|banner|channel|art|cover|header|tv"],
  ["yt-profile", "YouTube", "Channel profile picture", 800, 800, false, "youtube|yt|channel icon|profile|avatar|pfp|logo"],
  ["yt-watermark", "YouTube", "Video watermark", 150, 150, false, "youtube|yt|watermark|subscribe button|branding|channel watermark|logo"],
  ["yt-community-square", "YouTube", "Community post — square", 1080, 1080, false, "youtube|yt|community|community post|square|post|1:1"],
  ["yt-community-portrait", "YouTube", "Community post — portrait", 1080, 1350, false, "youtube|yt|community|community post|portrait|vertical|4:5"],
  ["yt-podcast", "YouTube", "Podcast cover", 3000, 3000, false, "youtube|yt|podcast|podcast cover|show art|album art|square"],

  // ---- Pinterest ----
  ["pin-standard", "Pinterest", "Standard pin", 1000, 1500, true, "pinterest|pin|tall|2:3|vertical|standard pin"],
  ["pin-square", "Pinterest", "Square pin", 1000, 1000, false, "pinterest|pin|square|1:1"],
  ["pin-portrait", "Pinterest", "Portrait pin", 1000, 1250, false, "pinterest|pin|portrait|4:5|vertical"],
  ["pin-long", "Pinterest", "Long pin", 1000, 2100, false, "pinterest|pin|long|tall|infographic|extended pin"],
  ["pin-video", "Pinterest", "Full-screen video pin", 1080, 1920, false, "pinterest|pin|video pin|vertical video|full bleed|fullscreen|9:16"],
  ["pin-cover", "Pinterest", "Profile cover", 1600, 900, false, "pinterest|pin|profile cover|cover|banner|header|16:9"],
  ["pin-profile", "Pinterest", "Profile picture", 280, 280, false, "pinterest|pin|profile|avatar|pfp|display picture"],

  // ---- Snapchat ----
  ["snap-story", "Snapchat", "Story / Snap", 1080, 1920, false, "snapchat|snap|story|snap|vertical|fullscreen|9:16"],
  ["snap-ad", "Snapchat", "Single image or video ad", 1080, 1920, false, "snapchat|snap|ad|ads|sponsored|vertical ad|9:16"],
  ["snap-filter", "Snapchat", "Geofilter", 1080, 2340, false, "snapchat|snap|geofilter|filter|overlay|location filter"],
  ["snap-profile", "Snapchat", "Public profile picture", 320, 320, false, "snapchat|snap|profile|avatar|pfp|public profile"],
  ["snap-lens-icon", "Snapchat", "Lens icon", 320, 320, false, "snapchat|snap|lens|lens icon|filter icon|ar lens"],

  // ---- Bluesky ----
  ["bsky-post", "Bluesky", "Landscape post image", 1600, 900, false, "bluesky|blue sky|bsky|skeet|post|feed|landscape|16:9"],
  ["bsky-square", "Bluesky", "Square post image", 1080, 1080, false, "bluesky|blue sky|bsky|square|post|1:1"],
  ["bsky-profile", "Bluesky", "Profile picture", 400, 400, false, "bluesky|blue sky|bsky|profile|avatar|pfp"],
  ["bsky-banner", "Bluesky", "Profile banner", 1500, 500, false, "bluesky|blue sky|bsky|banner|cover|header|profile"],

  // ---- Reddit ----
  ["reddit-post", "Reddit", "Post image", 1200, 628, false, "reddit|subreddit|post|link|preview|landscape|1.91:1"],
  ["reddit-square", "Reddit", "Square post", 1080, 1080, false, "reddit|subreddit|square|post|1:1"],
  ["reddit-community-icon", "Reddit", "Community icon", 256, 256, false, "reddit|subreddit|community icon|icon|avatar|logo"],
  ["reddit-banner", "Reddit", "Community banner", 1920, 384, false, "reddit|subreddit|banner|cover|header|community"],
  ["reddit-mobile-banner", "Reddit", "Mobile community banner", 1600, 480, false, "reddit|subreddit|mobile banner|cover|header|community"],

  // ---- Twitch ----
  ["twitch-video", "Twitch", "Stream / video canvas", 1920, 1080, false, "twitch|stream|streaming|video|canvas|overlay|16:9|1080p"],
  ["twitch-thumb", "Twitch", "Video thumbnail", 1280, 720, false, "twitch|stream|thumbnail|video cover|preview|16:9"],
  ["twitch-profile", "Twitch", "Profile picture", 800, 800, false, "twitch|stream|profile|avatar|pfp|channel icon"],
  ["twitch-banner", "Twitch", "Profile banner", 1200, 480, false, "twitch|stream|profile banner|cover|header|channel banner"],
  ["twitch-offline", "Twitch", "Offline screen", 1920, 1080, false, "twitch|stream|offline|offline screen|be right back|brb|ending screen|16:9"],
  ["twitch-panel", "Twitch", "Channel panel", 320, 100, false, "twitch|stream|panel|about panel|donate panel|schedule panel|channel panel"],

  // ---- Discord ----
  ["discord-profile", "Discord", "Profile picture", 512, 512, false, "discord|profile|avatar|pfp|user icon"],
  ["discord-profile-banner", "Discord", "Profile banner", 600, 240, false, "discord|profile banner|cover|header|nitro banner"],
  ["discord-server-icon", "Discord", "Server icon", 512, 512, false, "discord|server|server icon|guild icon|community icon|logo"],
  ["discord-server-banner", "Discord", "Server banner", 960, 540, false, "discord|server banner|guild banner|cover|header|16:9"],
  ["discord-event", "Discord", "Scheduled event cover", 800, 320, false, "discord|event|scheduled event|event cover|banner"],
  ["discord-invite-bg", "Discord", "Invite splash", 1920, 1080, false, "discord|invite|invite background|invite splash|server splash|16:9"],

  // ---- Messaging ----
  ["whatsapp-status", "Messaging", "WhatsApp Status", 1080, 1920, false, "whatsapp|wa|status|story|vertical|fullscreen|9:16"],
  ["whatsapp-profile", "Messaging", "WhatsApp profile picture", 500, 500, false, "whatsapp|wa|profile|avatar|pfp|display picture|dp"],
  ["whatsapp-product", "Messaging", "WhatsApp catalog product", 1000, 1000, false, "whatsapp|wa|catalog|product|shop|commerce|listing|square"],
  ["telegram-story", "Messaging", "Telegram Story", 1080, 1920, false, "telegram|tg|story|vertical|fullscreen|9:16"],
  ["telegram-profile", "Messaging", "Telegram profile picture", 512, 512, false, "telegram|tg|profile|avatar|pfp|channel photo|group photo"],
  ["slack-profile", "Messaging", "Slack profile picture", 512, 512, false, "slack|profile|avatar|pfp|headshot|workspace"],

  // ---- Google Business Profile ----
  ["gbp-post", "Google Business Profile", "Post image", 1200, 900, false, "google business|google business profile|gbp|gmb|post|update|offer|event|4:3"],
  ["gbp-cover", "Google Business Profile", "Cover photo", 1024, 576, false, "google business|google business profile|gbp|gmb|cover|banner|header|16:9"],
  ["gbp-logo", "Google Business Profile", "Logo", 720, 720, false, "google business|google business profile|gbp|gmb|logo|profile|avatar|square"],
  ["gbp-product", "Google Business Profile", "Product photo", 1200, 900, false, "google business|google business profile|gbp|gmb|product|menu|service|listing|4:3"],

  // ---- Web ----
  ["og-image", "Web", "Open Graph / link preview", 1200, 630, true, "og|opengraph|open graph|link preview|share card|social preview|meta|seo|twitter card|unfurl|website|slack preview"],
  ["web-hero", "Web", "Hero banner — 16:9", 1920, 1080, true, "hero|banner|header|website|web|full hd|1080p|landing|16:9|above the fold"],
  ["web-hero-wide", "Web", "Hero banner — wide", 1920, 800, false, "hero|banner|header|website|web|landing|wide hero|cinematic|desktop hero"],
  ["web-hero-mobile", "Web", "Mobile hero", 1080, 1350, false, "hero|mobile hero|website|web|landing|phone|portrait|4:5"],
  ["web-blog", "Web", "Blog header", 1200, 600, false, "blog|article|post|header|featured|cover|2:1|editorial"],
  ["web-featured", "Web", "Featured image", 1600, 900, false, "website|web|featured image|article image|blog cover|thumbnail|16:9"],
  ["web-card-landscape", "Web", "Content card — landscape", 800, 450, false, "website|web|card|content card|tile|thumbnail|landscape|16:9"],
  ["web-card-square", "Web", "Content card — square", 800, 800, false, "website|web|card|content card|tile|thumbnail|square|1:1"],
  ["web-favicon", "Web", "App icon / favicon master", 512, 512, false, "icon|favicon|app icon|logo|square|pwa|site icon"],
  ["web-apple-touch", "Web", "Apple touch icon", 180, 180, false, "apple touch icon|touch icon|ios web icon|safari icon|web app icon"],
  ["web-pwa-small", "Web", "PWA icon — 192", 192, 192, false, "pwa|progressive web app|manifest icon|android web icon|small app icon"],
  ["web-browser-extension", "Web", "Browser extension icon", 128, 128, false, "browser extension|chrome extension|firefox add-on|extension icon|toolbar icon"],

  // ---- Email ----
  ["email-header", "Email", "Newsletter header", 600, 200, false, "email|newsletter|mailchimp|klaviyo|header|banner|edm|email marketing"],
  ["email-hero", "Email", "Newsletter hero", 1200, 600, false, "email|newsletter|hero|banner|campaign|edm|2:1|retina"],
  ["email-product", "Email", "Product block", 600, 600, false, "email|newsletter|product|commerce|shop|square|product block"],
  ["email-feature", "Email", "Feature block", 600, 400, false, "email|newsletter|feature|content block|article|promotion"],
  ["email-divider", "Email", "Section divider", 600, 100, false, "email|newsletter|divider|section banner|strip|separator"],
  ["email-signature", "Email", "Email signature banner", 600, 150, false, "email|signature|email signature|footer banner|contact banner"],

  // ---- Display ads ----
  ["ad-billboard", "Display ads", "Billboard", 970, 250, true, "ad|ads|google|display|programmatic|billboard|banner|iab"],
  ["ad-super-leaderboard", "Display ads", "Super leaderboard", 970, 90, false, "ad|ads|google|display|programmatic|super leaderboard|banner|iab"],
  ["ad-leaderboard", "Display ads", "Leaderboard", 728, 90, true, "ad|ads|google|display|adwords|leaderboard|banner|top|iab"],
  ["ad-full-banner", "Display ads", "Full banner", 468, 60, false, "ad|ads|display|full banner|banner|iab|legacy banner"],
  ["ad-mobile", "Display ads", "Mobile banner", 320, 50, false, "ad|ads|google|display|mobile|banner|phone|iab"],
  ["ad-large-mobile", "Display ads", "Large mobile banner", 320, 100, false, "ad|ads|google|display|large mobile banner|mobile|phone|iab"],
  ["ad-medium", "Display ads", "Medium rectangle", 300, 250, true, "ad|ads|google|display|mrec|medium rectangle|box|sidebar|iab"],
  ["ad-large", "Display ads", "Large rectangle", 336, 280, false, "ad|ads|google|display|large rectangle|box|iab"],
  ["ad-square", "Display ads", "Square", 250, 250, false, "ad|ads|display|square ad|box|iab|1:1"],
  ["ad-small-square", "Display ads", "Small square", 200, 200, false, "ad|ads|display|small square|box|iab|1:1"],
  ["ad-halfpage", "Display ads", "Half page", 300, 600, true, "ad|ads|google|display|half page|sidebar|tall|iab"],
  ["ad-skyscraper", "Display ads", "Wide skyscraper", 160, 600, false, "ad|ads|google|display|skyscraper|tall|sidebar|iab"],
  ["ad-skyscraper-narrow", "Display ads", "Skyscraper", 120, 600, false, "ad|ads|display|skyscraper|narrow|tall|sidebar|iab"],
  ["ad-portrait", "Display ads", "Portrait", 300, 1050, false, "ad|ads|display|portrait ad|tall ad|sidebar|iab"],
  ["ad-responsive-landscape", "Display ads", "Responsive display — landscape", 1200, 628, true, "ad|ads|google ads|responsive display|landscape asset|marketing image|1.91:1"],
  ["ad-responsive-square", "Display ads", "Responsive display — square", 1200, 1200, false, "ad|ads|google ads|responsive display|square asset|marketing image|1:1"],

  // ---- Commerce ----
  ["shop-product", "Commerce", "Product photo — square", 2048, 2048, true, "product|shopify|store|ecommerce|e-commerce|catalog|listing|square|shop|pdp"],
  ["shop-product-portrait", "Commerce", "Product photo — portrait", 1600, 2000, false, "product|shopify|store|ecommerce|e-commerce|catalog|listing|portrait|4:5|fashion"],
  ["shop-collection", "Commerce", "Collection banner", 1800, 1000, false, "shopify|store|ecommerce|collection|category|banner|hero|plp"],
  ["shop-og", "Commerce", "Store link preview", 1200, 630, false, "shopify|store|ecommerce|open graph|og|link preview|social sharing"],
  ["amazon-main", "Commerce", "Amazon main image", 2000, 2000, true, "amazon|marketplace|listing|product|main image|hero image|zoom|square"],
  ["amazon-a-plus", "Commerce", "Amazon A+ module", 970, 600, false, "amazon|a+|a plus|enhanced brand content|ebc|module|product page"],
  ["etsy-listing", "Commerce", "Etsy listing photo", 2700, 2025, false, "etsy|listing|product|marketplace|shop|4:3|listing photo"],
  ["etsy-shop-banner", "Commerce", "Etsy big shop banner", 3360, 840, false, "etsy|shop banner|store banner|cover|header|4:1"],
  ["ebay-listing", "Commerce", "eBay listing photo", 1600, 1600, false, "ebay|listing|product|marketplace|main image|square"],
  ["ebay-billboard", "Commerce", "eBay store billboard", 1280, 290, false, "ebay|store|billboard|banner|cover|header"],
  ["walmart-product", "Commerce", "Walmart product image", 2000, 2000, false, "walmart|marketplace|listing|product|main image|square"],
  ["merchant-product", "Commerce", "Google Merchant product", 1200, 1200, false, "google merchant|merchant center|shopping ad|product feed|product image|square"],
  ["marketplace-landscape", "Commerce", "Marketplace lifestyle image", 1600, 1200, false, "marketplace|product|lifestyle image|secondary image|gallery|4:3"],
  ["product-detail", "Commerce", "Product detail close-up", 2000, 2500, false, "product|detail image|close up|feature image|pdp|portrait|4:5"],

  // ---- App stores ----
  ["appstore-icon", "App stores", "Apple App Store icon", 1024, 1024, true, "apple|app store|ios|iphone|ipad|app icon|store icon|1024"],
  ["appstore-iphone", "App stores", "iPhone screenshot — portrait", 1290, 2796, false, "apple|app store|ios|iphone|screenshot|portrait|phone screenshot"],
  ["appstore-ipad", "App stores", "iPad screenshot — portrait", 2048, 2732, false, "apple|app store|ios|ipad|screenshot|tablet|portrait"],
  ["play-icon", "App stores", "Google Play icon", 512, 512, true, "google play|play store|android|app icon|store icon|launcher icon"],
  ["play-feature", "App stores", "Google Play feature graphic", 1024, 500, false, "google play|play store|android|feature graphic|store banner|promo banner"],
  ["play-phone", "App stores", "Google Play phone screenshot", 1080, 1920, false, "google play|play store|android|phone screenshot|screenshot|portrait|9:16"],
  ["play-tv", "App stores", "Google TV banner", 1280, 720, false, "google play|android tv|google tv|tv banner|leanback|16:9"],

  // ---- Presentations & video ----
  ["slide-widescreen", "Presentations & video", "Presentation — widescreen", 1920, 1080, true, "presentation|slides|powerpoint|ppt|pptx|google slides|keynote|widescreen|16:9"],
  ["slide-standard", "Presentations & video", "Presentation — standard", 1024, 768, false, "presentation|slides|powerpoint|ppt|pptx|google slides|keynote|standard|4:3"],
  ["video-8k", "Presentations & video", "8K UHD video", 7680, 4320, false, "video|8k|uhd|4320p|16:9"],
  ["video-4k", "Presentations & video", "4K UHD video", 3840, 2160, true, "video|4k|uhd|2160p|16:9"],
  ["video-2k", "Presentations & video", "2K / QHD video", 2560, 1440, false, "video|2k|qhd|1440p|16:9"],
  ["video-1080", "Presentations & video", "Full HD video", 1920, 1080, true, "video|full hd|fhd|1080p|hd|16:9"],
  ["video-720", "Presentations & video", "HD video", 1280, 720, false, "video|hd|720p|16:9"],
  ["video-square", "Presentations & video", "Square video", 1080, 1080, false, "video|square video|social video|1:1"],
  ["video-vertical", "Presentations & video", "Vertical video", 1080, 1920, true, "video|vertical video|portrait video|mobile video|9:16|short form"],
  ["video-cinema", "Presentations & video", "DCI 4K cinema", 4096, 2160, false, "video|cinema|dci|4k cinema|scope|theatrical"],

  // ---- Print ----
  ["print-a3", "Print", "A3 at 300 dpi", 3508, 4961, false, "print|a3|page|poster|flyer|300dpi|dpi"],
  ["print-a4", "Print", "A4 at 300 dpi", 2480, 3508, true, "print|a4|page|poster|flyer|300dpi|dpi"],
  ["print-a5", "Print", "A5 at 300 dpi", 1748, 2480, false, "print|a5|flyer|leaflet|page|300dpi"],
  ["print-a6", "Print", "A6 at 300 dpi", 1240, 1748, false, "print|a6|postcard|flyer|leaflet|page|300dpi"],
  ["print-letter", "Print", "US Letter at 300 dpi", 2550, 3300, true, "print|letter|us letter|page|flyer|8.5x11|300dpi"],
  ["print-legal", "Print", "US Legal at 300 dpi", 2550, 4200, false, "print|legal|us legal|page|8.5x14|300dpi"],
  ["print-tabloid", "Print", "Tabloid / Ledger at 300 dpi", 3300, 5100, false, "print|tabloid|ledger|11x17|poster|newspaper|300dpi"],
  ["print-half-letter", "Print", "Half Letter at 300 dpi", 1650, 2550, false, "print|half letter|5.5x8.5|booklet|notebook|page|300dpi"],
  ["print-photo", "Print", "6 × 4 photo at 300 dpi", 1800, 1200, false, "print|photo|6x4|4x6|postcard|3:2|300dpi"],
  ["print-photo-5x7", "Print", "7 × 5 photo at 300 dpi", 2100, 1500, false, "print|photo|7x5|5x7|photo print|300dpi"],
  ["print-photo-8x10", "Print", "10 × 8 photo at 300 dpi", 3000, 2400, false, "print|photo|10x8|8x10|portrait print|300dpi"],
  ["print-card", "Print", "Business card at 300 dpi", 1050, 600, true, "print|business card|card|name card|3.5x2|300dpi"],
  ["print-card-bleed", "Print", "Business card with bleed", 1125, 675, false, "print|business card|card|name card|bleed|trim|3.75x2.25|300dpi"],
  ["print-postcard", "Print", "Postcard — 6 × 4", 1800, 1200, false, "print|postcard|mailer|direct mail|6x4|4x6|300dpi"],
  ["print-rack-card", "Print", "Rack card — 4 × 9", 1200, 2700, false, "print|rack card|dl flyer|4x9|tourism brochure|hotel rack|300dpi"],
  ["print-trifold", "Print", "Tri-fold brochure — Letter", 3300, 2550, false, "print|tri fold|trifold|brochure|letter landscape|folded leaflet|300dpi"],
  ["print-poster-18x24", "Print", "Poster — 18 × 24", 5400, 7200, false, "print|poster|18x24|large poster|300dpi"],
  ["print-poster-24x36", "Print", "Poster — 24 × 36", 7200, 10800, false, "print|poster|24x36|movie poster|large format|300dpi"],

  // ---- Podcast & music ----
  ["podcast-cover", "Podcast & music", "Podcast cover", 3000, 3000, true, "podcast|podcast cover|show art|cover art|apple podcasts|spotify podcast|square"],
  ["album-cover", "Podcast & music", "Album cover", 3000, 3000, true, "album|album cover|cover art|music|record|single cover|square"],
  ["spotify-canvas", "Podcast & music", "Spotify Canvas", 1080, 1920, false, "spotify|canvas|spotify canvas|vertical video|loop|9:16"],
  ["spotify-playlist", "Podcast & music", "Spotify playlist cover", 640, 640, false, "spotify|playlist|playlist cover|cover art|square"],
  ["soundcloud-profile", "Podcast & music", "SoundCloud profile picture", 1000, 1000, false, "soundcloud|profile|avatar|pfp|artist image|square"],
  ["soundcloud-header", "Podcast & music", "SoundCloud header", 2480, 520, false, "soundcloud|header|banner|cover|artist banner"],

  // ---- Events & calls ----
  ["zoom-background", "Events & calls", "Zoom virtual background", 1920, 1080, true, "zoom|virtual background|video call|meeting background|webcam background|16:9"],
  ["teams-background", "Events & calls", "Microsoft Teams background", 1920, 1080, false, "teams|microsoft teams|virtual background|meeting background|video call|16:9"],
  ["webinar-cover", "Events & calls", "Webinar cover", 1920, 1080, false, "webinar|virtual event|event cover|registration page|presentation cover|16:9"],
  ["eventbrite-cover", "Events & calls", "Event listing cover", 2160, 1080, false, "eventbrite|event|event cover|event listing|ticketing|2:1"],
  ["digital-signage", "Events & calls", "Digital signage — landscape", 1920, 1080, false, "digital signage|screen|display|tv graphic|menu board|landscape|16:9"],
];

export const PRESETS: readonly Preset[] = RAW_PRESETS.map(
  ([id, group, name, w, h, hot, keywords]) =>
    enrichPreset({ id, group, name, w, h, hot, keywords }),
);

// Ratio shorthand people type directly. Each ratio maps to a concrete,
// practical canvas instead of an abstract shape.
export const RATIO_SIZES: readonly { readonly ratio: number; readonly w: number; readonly h: number }[] = [
  { ratio: 1 / 1, w: 1080, h: 1080 },
  { ratio: 4 / 5, w: 1080, h: 1350 },
  { ratio: 5 / 4, w: 1350, h: 1080 },
  { ratio: 9 / 16, w: 1080, h: 1920 },
  { ratio: 16 / 9, w: 1920, h: 1080 },
  { ratio: 3 / 2, w: 1800, h: 1200 },
  { ratio: 2 / 3, w: 1200, h: 1800 },
  { ratio: 4 / 3, w: 1600, h: 1200 },
  { ratio: 3 / 4, w: 1200, h: 1600 },
  { ratio: 5 / 7, w: 1500, h: 2100 },
  { ratio: 7 / 5, w: 2100, h: 1500 },
  { ratio: 21 / 9, w: 2520, h: 1080 },
  { ratio: 32 / 9, w: 3840, h: 1080 },
  { ratio: 2 / 1, w: 1600, h: 800 },
  { ratio: 1 / 2, w: 1000, h: 2000 },
  { ratio: 3 / 1, w: 1800, h: 600 },
  { ratio: 4 / 1, w: 1600, h: 400 },
  { ratio: 5 / 2, w: 2000, h: 800 },
  { ratio: 1.91 / 1, w: 1200, h: 628 },
  { ratio: 1 / 1.91, w: 628, h: 1200 },
];

export const HOT: readonly Preset[] = PRESETS.filter((preset) => preset.hot);